title: Learning Emacs and shit
email: mijoch@gmail.com
description: >
  Learning Emacs and shit
baseurl: "/emacs/" # the subpath of your site, e.g. /blog/
url: "http://chantastic.github.io"
twitter_username: chantastic
github_username:  chantastic

# Build settings
markdown: kramdown